# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -L 'https://get.spectralops.io/latest/sh?dsn=${SPECTRAL_DSN}' | sudo sh
  displayName: 'Install Spectral'

- script: spectral scan
  displayName: 'Spectral Scan'
