steps:
- name: gcr.io/cloud-builders/gcloud
  id: Spectral
  entrypoint: bash
  args:
  - -c
  - |
    curl -L "https://get.spectralops.io/latest/sh?dsn=$$SPECTRAL_DSN" | sh
    spectral scan
  secretEnv: ['SPECTRAL_DSN']
availableSecrets:
  secretManager:
  - versionName: projects/PROJECT_ID/secrets/SPECTRAL_DSN/versions/latest
    env: SPECTRAL_DSN
