#steps:
#  - name: gcr.io/cloud-builders/gcloud
#    entrypoint: "bash"
#    args:
#      - "-c"
#      - |
#          curl -L "https://get.spectralops.io/latest/sh?dsn=$$SPECTRAL_DSN" | sh
#          spectral scan
#    secretEnv: ['SPECTRAL_DSN']
steps:
- name: gcr.io/cloud-builders/gcloud
  id: Spectral
  entrypoint: bash
  args:
  - -c
  - curl -L "https://get.spectralops.io/latest/sh?dsn=$$SPECTRAL_DSN" | sh
  - spectral scan
  secretEnv: ['SPECTRAL_DSN']
availableSecrets:
  secretManager:
  - versionName: projects/1084744508735/secrets/SPECTRAL_DSN/versions/latest
    env: SPECTRAL_DSN
